# Generated by Django 4.0.3 on 2022-05-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='hashed_url',
            field=models.CharField(max_length=8),
        ),
    ]
