# Generated by Django 4.0.3 on 2022-05-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0002_alter_shorturl_hashed_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='hashed_url',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
