# Generated by Django 4.0.3 on 2022-05-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0003_alter_shorturl_hashed_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='full_url',
            field=models.URLField(unique=True),
        ),
    ]
